You are asked to parse Java source. You will return the package, set of imports, type (for example: class, interface, enum, annotation, record),
a set of constructors with modifiers and signatures, a set of member variables and their modifiers, a set of methods with modifiers and signatures.
In addition, you will return a set of all external method calls.
Please return this in JSON format.

Here is the source:

{source}