services:
  zipkin:
    image: openzipkin/zipkin-slim:3
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - net
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - net

volumes:
  grafana-storage: {}
