services:
  postgres:
    image: ghcr.io/postgresml/postgresml:2.9.3
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    command: sudo -u postgresml psql -d postgresml
    stdin_open: true
    tty: true
    networks:
      - net
  zipkin:
    image: openzipkin/zipkin-slim:3
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - net
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - net

volumes:
  grafana-storage: {}
  postgres-data:
    driver: local

networks:
  net:
    driver: bridge