include:
  - docker-compose.observability.yml

services:
  redis:
    image: redis/redis-stack-server:7.4.0-v1
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - net

volumes:
  redis-data:
    driver: local

networks:
  net:
    driver: bridge