spring:
  profiles:
    active: default,groq-cloud

  application:
    name: robert

  threads:
    virtual:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: groq-cloud
    import: "optional:file:./config/creds.yml"

  ai:
      openai:
        base_url: https://api.groq.com/openai
        chat:
          options:
            model: llama-3.1-70b-versatile
            temperature: 0.5

---

spring:
  config:
    activate:
      on-profile: ollama

  ai:
    ollama:
      chat:
        options:
          model: llama3.1:70b
          top-k: 10
          top-p: 0.5
