spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
      - name: pgvector
        image: pgvector/pgvector:pg16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: pgvector
        volumeMounts:
        - name: pgvector-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgvector-data
        emptyDir: {}
